/**
 * Dependency, build, cache, tooling, and generated-source directories omitted
 * from every CodeGraph index unless a root .gitignore negation revives them.
 *
 * This runtime-neutral source of truth is shared with browser-local indexing.
 */
const DEFAULT_IGNORE_DIRS = [
  'node_modules',
  'bower_components',
  'jspm_packages',
  'web_modules',
  '.yarn',
  '.pnpm-store',
  '.next',
  '.nuxt',
  '.svelte-kit',
  '.turbo',
  '.vite',
  '.parcel-cache',
  '.angular',
  '.docusaurus',
  'storybook-static',
  '.vinxi',
  '.nitro',
  'out-tsc',
  '.vercel',
  '.netlify',
  '.wrangler',
  'dist',
  'build',
  'out',
  '.output',
  'coverage',
  '.nyc_output',
  '__pycache__',
  '__pypackages__',
  '.venv',
  'venv',
  '.pixi',
  '.pdm-build',
  '.mypy_cache',
  '.pytest_cache',
  '.ruff_cache',
  '.tox',
  '.nox',
  '.hypothesis',
  '.ipynb_checkpoints',
  '.eggs',
  'target',
  '.gradle',
  'obj',
  'vendor',
  '.build',
  'Pods',
  'Carthage',
  'DerivedData',
  '.swiftpm',
  '.dart_tool',
  '.pub-cache',
  '.cxx',
  '.externalNativeBuild',
  'vcpkg_installed',
  '.bloop',
  '.metals',
  'lua_modules',
  '.luarocks',
  '__history',
  '__recovery',
  '.cache',
] as const;

const ANDROID_RES_TYPES = [
  'anim',
  'animator',
  'color',
  'drawable',
  'font',
  'layout',
  'menu',
  'mipmap',
  'navigation',
  'transition',
  'values',
  'xml',
] as const;

export const DEFAULT_IGNORE_PATTERNS: readonly string[] = [
  ...DEFAULT_IGNORE_DIRS.map((directory) => `${directory}/`),
  '*.egg-info/',
  'cmake-build-*/',
  'bazel-*/',
  ...ANDROID_RES_TYPES.map((type) => `**/res/${type}*/`),
];
