import type { Language } from '../types';

/**
 * File extension to language mapping shared by Node and browser extraction.
 *
 * Keep this module runtime-neutral: the browser worker imports it directly.
 */
export const EXTENSION_MAP: Record<string, Language> = {
  '.ts': 'typescript',
  '.tsx': 'tsx',
  '.mts': 'typescript',
  '.cts': 'typescript',
  '.ets': 'arkts',
  '.js': 'javascript',
  '.mjs': 'javascript',
  '.cjs': 'javascript',
  '.xsjs': 'javascript',
  '.xsjslib': 'javascript',
  '.jsx': 'jsx',
  '.py': 'python',
  '.pyw': 'python',
  '.go': 'go',
  '.rs': 'rust',
  '.java': 'java',
  '.c': 'c',
  '.h': 'c',
  '.cpp': 'cpp',
  '.cc': 'cpp',
  '.cxx': 'cpp',
  '.hpp': 'cpp',
  '.hxx': 'cpp',
  '.cs': 'csharp',
  '.cshtml': 'razor',
  '.razor': 'razor',
  '.php': 'php',
  '.module': 'php',
  '.install': 'php',
  '.theme': 'php',
  '.inc': 'php',
  '.yml': 'yaml',
  '.yaml': 'yaml',
  '.twig': 'twig',
  '.rb': 'ruby',
  '.rake': 'ruby',
  '.swift': 'swift',
  '.kt': 'kotlin',
  '.kts': 'kotlin',
  '.dart': 'dart',
  '.liquid': 'liquid',
  '.svelte': 'svelte',
  '.vue': 'vue',
  '.astro': 'astro',
  '.r': 'r',
  '.pas': 'pascal',
  '.dpr': 'pascal',
  '.dpk': 'pascal',
  '.lpr': 'pascal',
  '.dfm': 'pascal',
  '.fmx': 'pascal',
  '.scala': 'scala',
  '.sc': 'scala',
  '.lua': 'lua',
  '.luau': 'luau',
  '.m': 'objc',
  '.mm': 'objc',
  '.sol': 'solidity',
  '.cfc': 'cfml',
  '.cfm': 'cfml',
  '.cfs': 'cfscript',
  '.metal': 'cpp',
  '.cu': 'cpp',
  '.cuh': 'cpp',
  '.nix': 'nix',
  '.xml': 'xml',
  '.cbl': 'cobol',
  '.cob': 'cobol',
  '.cobol': 'cobol',
  '.cpy': 'cobol',
  '.vb': 'vbnet',
  '.erl': 'erlang',
  '.hrl': 'erlang',
  '.escript': 'erlang',
  '.ml': 'ocaml',
  '.mli': 'ocaml',
  '.properties': 'properties',
  '.tf': 'terraform',
  '.tfvars': 'terraform',
  '.tofu': 'terraform',
};
