/**
 * `ensureCodegraphIgnored` — `codegraph init` auto-adds `.codegraph/` to the
 * project's `.gitignore` so the local index (and, once embeddings are
 * configured, the vectors — tens of MB, fully regenerated by init/sync) is
 * never committed.
 *
 * The helper is advisory (never throws), idempotent, and only touches real git
 * repositories. No git binary is needed here: a `.git` directory (normal repo)
 * or a `.git` file (worktree/submodule gitdir pointer) is enough to simulate
 * one.
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { ensureCodegraphIgnored } from '../src/utils';

describe('ensureCodegraphIgnored', () => {
  let tempDir: string;

  beforeEach(() => {
    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'codegraph-gitignore-'));
  });

  afterEach(() => {
    fs.rmSync(tempDir, { recursive: true, force: true });
  });

  const gitignorePath = () => path.join(tempDir, '.gitignore');
  const makeGitDir = () => fs.mkdirSync(path.join(tempDir, '.git'));
  const makeGitFile = () =>
    fs.writeFileSync(
      path.join(tempDir, '.git'),
      'gitdir: /repo/.git/worktrees/wt\n'
    );

  it('does nothing and returns false when the directory is not a git repo', () => {
    const result = ensureCodegraphIgnored(tempDir);

    expect(result).toBe(false);
    expect(fs.existsSync(gitignorePath())).toBe(false);
  });

  it('creates .gitignore with a .codegraph/ entry when none exists (git dir)', () => {
    makeGitDir();

    const result = ensureCodegraphIgnored(tempDir);

    expect(result).toBe(true);
    expect(fs.existsSync(gitignorePath())).toBe(true);
    // .codegraph/ lands on its own line.
    expect(fs.readFileSync(gitignorePath(), 'utf-8')).toMatch(/^\.codegraph\/$/m);
  });

  it('appends to an existing .gitignore, preserving content, with clean newline handling', () => {
    makeGitDir();
    // Deliberately NOT ending in a newline — the append must not glue our
    // entry onto the last existing line.
    const original = 'node_modules\n*.log';
    fs.writeFileSync(gitignorePath(), original);

    const result = ensureCodegraphIgnored(tempDir);

    expect(result).toBe(true);
    const content = fs.readFileSync(gitignorePath(), 'utf-8');
    // Original content preserved verbatim at the head of the file.
    expect(content.startsWith(original)).toBe(true);
    // .codegraph/ on its own line, not glued onto `*.log`.
    expect(content).toMatch(/^\.codegraph\/$/m);
    expect(content).not.toContain('*.log.codegraph');
    // Exactly one newline separates the old last line from our appended block.
    expect(content).toContain('*.log\n# CodeGraph');
  });

  it.each(['.codegraph', '.codegraph/', '/.codegraph/', '.codegraph/   '])(
    'returns false and leaves the file byte-unchanged when already ignored via %j',
    (entry) => {
      makeGitDir();
      const original = `node_modules\n${entry}\n`;
      fs.writeFileSync(gitignorePath(), original);
      const before = fs.readFileSync(gitignorePath());

      const result = ensureCodegraphIgnored(tempDir);

      const after = fs.readFileSync(gitignorePath());
      expect(result).toBe(false);
      expect(after.equals(before)).toBe(true);
    }
  );

  it('is idempotent: a second call is a no-op and leaves a single entry', () => {
    makeGitDir();

    expect(ensureCodegraphIgnored(tempDir)).toBe(true);
    const afterFirst = fs.readFileSync(gitignorePath(), 'utf-8');

    expect(ensureCodegraphIgnored(tempDir)).toBe(false);
    const afterSecond = fs.readFileSync(gitignorePath(), 'utf-8');

    // Second call changed nothing.
    expect(afterSecond).toBe(afterFirst);
    // Exactly one .codegraph/ line total.
    const occurrences = afterSecond
      .split('\n')
      .filter((line) => line.trim() === '.codegraph/').length;
    expect(occurrences).toBe(1);
  });

  it('treats a .git FILE (worktree/submodule) as a git repo', () => {
    makeGitFile();

    const result = ensureCodegraphIgnored(tempDir);

    expect(result).toBe(true);
    expect(fs.existsSync(gitignorePath())).toBe(true);
    expect(fs.readFileSync(gitignorePath(), 'utf-8')).toMatch(/^\.codegraph\/$/m);
  });
});
